service: tvshows-info

provider:
  name: aws
  runtime: python3.8
  profile: default
  region: us-east-2
  stage: prod # default stage, for multi stage deployment use ${opt:stage, 'dev'}
  versionFunctions: false

  environment:
    #tmdb
    TMDB_API_KEY: ${file(./secrets.env.yml):tmdb.TMDB_API_KEY}
    #airTable
    AIRTABLE_URL : ${file(./secrets.env.yml):airTable.AIRTABLE_URL}
    AIRTABLE_API_KEY: ${file(./secrets.env.yml):airTable.AIRTABLE_API_KEY}
    BASE_KEY: ${file(./secrets.env.yml):airTable.BASE_KEY}
    TBL_TV_SHOWS: ${file(./secrets.env.yml):airTable.TBL_TV_SHOWS}
    TBL_RELATED_TV_SHOWS: ${file(./secrets.env.yml):airTable.TBL_RELATED_TV_SHOWS}

plugins:
  - serverless-step-functions
 
functions:
  # getting TV show info from themoviedb api
  getTVShowsInfo:
    handler: lambdas/endpoints/getTVShowsInfo.handler
    description: Getting TV show info from themoviedb api
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-requests:9
      - arn:aws:lambda:us-east-2:877428826965:layer:tmdbsimple:3

  # updating TV show info
  updateTVShowInfo:
    handler: lambdas/stepFunctionLambdas/updateTVShowInfo.handler
    description: Updating TV show info    
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-requests:9

  # getting related TV show info from themoviedb api
  relatedTVShows:
    handler: lambdas/stepFunctionLambdas/relatedTVShows.handler
    description: Getting related TV show info from themoviedb api
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-requests:9
      - arn:aws:lambda:us-east-2:877428826965:layer:tmdbsimple:3

stepFunctions:
  validate: true
  stateMachines:
    updateTVShowInfoStateMachine:
      name: updateTVShowInfoStateMachine
      events:
        - http:
              path: upate-tv-show-info
              method: POST
      definition: ${file(./stepFunction.yml)}



